### ISSUE TITLE
JDBC sink fails to bootstrap in PCF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#109]
As a user, I'm using the JDBC sink in a stream definition, but the stream deployment fails with the following exception.

```
0]      OUT 2015-11-12 22:31:39.446  INFO 28 --- [           main] o.s.c.s.m.l.ModuleLauncherApplication    : Started ModuleLauncherApplication in 59.7 seconds (JVM running for 60.336)
2015-11-12T14:31:39.52-0800 [HEALTH/0]   OUT healthcheck failed
2015-11-12T14:31:39.52-0800 [HEALTH/0]   OUT Exit status 1
2015-11-12T14:31:39.52-0800 [CELL/0]     ERR Timed out after 1m0s: health check never passed.
2015-11-12T14:31:39.53-0800 [CELL/0]     OUT Exit status 0
2015-11-12T14:31:39.69-0800 [APP/0]      ERR java.lang.reflect.InvocationTargetException
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.lang.reflect.Method.invoke(Method.java:497)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.lang.Thread.run(Thread.java:745)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.cloudfoundry.reconfiguration.spring.CloudPropertySourceApplicationContextInitializer
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:396)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:373)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:251)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:227)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at org.springframework.cloud.stream.module.jdbc.JdbcSinkApplication.main(JdbcSinkApplication.java:31)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	... 6 more
2015-11-12T14:31:39.69-0800 [APP/0]      ERR Caused by: java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextInitializer
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.lang.ClassLoader.defineClass1(Native Method)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.security.AccessController.doPrivileged(Native Method)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
2015-11-12T14:31:39.69-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:389)
2015-11-12T14:31:39.70-0800 [APP/0]      ERR 	... 12 more
2015-11-12T14:31:39.70-0800 [APP/0]      ERR Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContextInitializer
2015-11-12T14:31:39.70-0800 [APP/0]      ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2015-11-12T14:31:39.70-0800 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2015-11-12T14:31:39.70-0800 [APP/0]      ERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2015-11-12T14:31:39.70-0800 [APP/0]      ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2015-11-12T14:31:39.70-0800 [APP/0]      ERR 	... 27 more
```

**Comment by trisberg** [comment]
This is an issue with the module launcher. Created issue here: https://github.com/spring-cloud/spring-cloud-stream/issues/204
