### ISSUE TITLE
Concurrent access issue in websocket sink module

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream-modules#113]
As witnessed in https://travis-ci.org/spring-cloud/spring-cloud-stream-modules/builds/91894403

That whole static thing being accessed from same package classes seems phony anyway

**Comment by markpollack** [comment]
closed by accident in PR comment.

**Comment by markpollack** [comment]
This is still a persistent error in travis (but not bamboo CI builds)

```
Running org.springframework.cloud.stream.module.websocket.sink.WebsocketSinkIntegrationTests
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 27.248 sec <<< FAILURE! - in org.springframework.cloud.stream.module.websocket.sink.WebsocketSinkIntegrationTests
testSingleMessageMultipleSubscribers(org.springframework.cloud.stream.module.websocket.sink.WebsocketSinkIntegrationTests)  Time elapsed: 10.059 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.springframework.cloud.stream.module.websocket.sink.WebsocketSinkIntegrationTests$WebsocketSinkClientHandler.await(WebsocketSinkIntegrationTests.java:198)
	at org.springframework.cloud.stream.module.websocket.sink.WebsocketSinkIntegrationTests.testSingleMessageMultipleSubscribers(WebsocketSinkIntegrationTests.java:110)
```

from https://travis-ci.org/spring-cloud/spring-cloud-stream-modules/builds/96364432

**Comment by ericbottard** [comment]
I've seen it locally as well. Good thing "websocket" starts with a w, and this is the last module... But there is definitely something going on there

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#60
