### ISSUE TITLE
PMML processor doesn't work

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#166]
As a user, I'm trying to use `pmml` processor, but I'm getting an exception while consuming `json` from an upstream module and augmenting the payload with predicted outcomes. 

**stream:**
```
stream create --name pmml1 --definition "http --server.port=9001 | pmml --modelName=iris-flower-classifier-1 --modelLocation=file:/Users/sanandan/Downloads/test.xml --inputs='Sepal.Length=sepalLength,Sepal.Width=sepalWidth,Petal.Length=petalLength,Petal.Width=petalWidth' --outputs='Predicted_Species=predictedSpecies' --inputType='application/json' | log" --deploy
```
**post:**
```
http post --target http://localhost:9001 --contentType application/json --data "{ \"sepalLength\": 6.4, \"sepalWidth\": 3.2, \"petalLength\":4.5, \"petalWidth\":1.5 }"
```

**error:**
```
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1010E:(pos 8): Property or field 'Species' cannot be set on object of type 'java.lang.String' - maybe not public?
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.writeProperty(PropertyOrFieldReference.java:270) ~[spring-expression-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$300(PropertyOrFieldReference.java:46) ~[spring-expression-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.setValue(PropertyOrFieldReference.java:384) ~[spring-expression-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.expression.spel.ast.CompoundExpression.setValue(CompoundExpression.java:95) ~[spring-expression-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.expression.spel.standard.SpelExpression.setValue(SpelExpression.java:422) ~[spring-expression-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.cloud.stream.module.pmml.processor.PmmlProcessor.evaluate(PmmlProcessor.java:130) ~[pmml-processor-1.0.0.BUILD-SNAPSHOT-exec.jar!/:1.0.0.BUILD-SNAPSHOT]
```

**Comment by ericbottard** [comment]
@sabbyanandan With https://github.com/spring-cloud/spring-cloud-stream/pull/291 applied, the following definition will work:

```
stream create --name pmml1 
--definition "http --server.port=9001 
| pmml --modelLocation=https://raw.githubusercontent.com/spring-cloud/spring-cloud-stream-modules/master/pmml-processor/src/test/resources/iris-flower-classification-naive-bayes-1.pmml.xml 
--inputs='Sepal.Length=sepalLength,Sepal.Width=sepalWidth,Petal.Length=petalLength,Petal.Width=petalWidth' 
--outputs='Predicted_Species=predictedSpecies' 
--inputType='application/x-spring-tuple' 
--outputType='application/json'
| log" --deploy
```

Setting `outputType` to json is currently necessary as the processor will try to add all results no matter what, and one of them is of a type that ships with jpmml. By using tuple, it would get serialized, but the log processor does not know about it. Using json, its constituent parts are serialized individually, as a Map

**Comment by sabbyanandan** [comment]
@ericbottard: With your SCS branch (`issue_290_mutable_tuple`) changes and the latest from SCDF (via: `mvn clean -U install`), I'm getting a different error this time. I used the same stream definition as you posted above.

**error:**
```
org.springframework.messaging.MessageHandlingException: nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1010E:(pos 8): Property or field 'Species' cannot be set on object of type 'org.springframework.cloud.stream.tuple.DefaultTuple' - maybe not public?
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:96) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:89) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:99) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:147) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:120) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:442) [spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:392) [spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:115) [spring-messaging-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:45) [spring-messaging-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:105) [spring-messaging-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:231) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:154) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:102) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:105) ~[spring-integration-core-4.2.4.RELEASE.jar!/:na]
```

**Comment by ericbottard** [comment]
Sorry, there is a slight mistake in the stream def. Here's the correct one:
```
stream create --name pmml1 --definition "http --server.port=9001 | pmml --modelLocation=https://raw.githubusercontent.com/spring-cloud/spring-cloud-stream-modules/master/pmml-processor/src/test/resources/iris-flower-classification-naive-bayes-1.pmml.xml --inputs='Sepal.Length=sepalLength,Sepal.Width=sepalWidth,Petal.Length=petalLength,Petal.Width=petalWidth' --outputs='Predicted_Species=payload.predictedSpecies' --inputType='application/x-spring-tuple' --outputType='application/json'| log" --deploy
```

**Comment by markpollack** [comment]
I could not have picked up the right snapshot, but with changing TupleBuilder.tuple() to be the immutable tuple, I think it is resulting in the same error.  The IT tests pass, but those don't look to take any --inputType convertion into account.  Need to investigate more.

**Comment by markpollack** [comment]
If that is the case, we should revert back to the logic that was there in XD wrt to prob just creating another copy of the original tuple for output and adding the new fields to that copy.

**Comment by ericbottard** [comment]
Sadly we can't with a SpEL PropertyAccessor

**Comment by markpollack** [comment]
Obviously this worked in XD that had immutable tuples.  Can we get this merged with whatever approach was used there.  Some folks are waiting on this internally.  We can come back to tuple changes and type conversion in another iteration decoupled from pmml support.  Am I not understanding the situation correctly?
