### ISSUE TITLE
Cassandra sink fails to bootstrap in CF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-modules#195]
As a user, I'm trying to ingest data using `cassandra` sink application; however, the app doesn't successfully bootstrap and fails with an exception.

**stream:**
```
stream create cassandrastream --definition "http --spring.cloud.stream.bindings.output.contentType='application/json' | cassandra --ingestQuery='insert into book (id, isbn, title, author) values (uuid(), ?, ?, ?)' --queryType=INSERT --spring.cassandra.username='<USERNAME>' --spring.cassandra.password='<PASSWORD>' --spring.cassandra.port=<PORT> --spring.cassandra.contactPoints=<HOST> --spring.cassandra.keyspace='<KEYSPACE>'" --deploy
```

**error:**
```
2016-02-22T06:49:50.22-0800 [APP/0]      ERR Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
2016-02-22T06:49:50.22-0800 [APP/0]      ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
2016-02-22T06:49:50.22-0800 [APP/0]      ERR 	at java.lang.Thread.run(Thread.java:745)
2016-02-22T06:49:50.22-0800 [APP/0]      ERR Caused by: java.lang.reflect.InvocationTargetException
2016-02-22T06:49:50.22-0800 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-02-22T06:49:50.22-0800 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-02-22T06:49:50.22-0800 [APP/0]      ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-02-22T06:49:50.22-0800 [APP/0]      ERR 	at java.lang.reflect.Method.invoke(Method.java:497)
2016-02-22T06:49:50.22-0800 [APP/0]      ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	... 1 more
2016-02-22T06:49:50.23-0800 [APP/0]      ERR Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraSinkConfiguration' defined in URL [jar:file:/home/vcap/.m2/repository/org/springframework/cloud/stream/module/cassandra-sink/1.0.0.BUILD-SNAPSHOT/cassandra-sink-1.0.0.BUILD-SNAPSHOT-exec.jar!/org/springframework/cloud/stream/module/cassandra/sink/CassandraSinkConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bridgeMessageHandler' defined in class path resource [org/springframework/cloud/stream/module/cassandra/sink/CassandraSinkConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.messaging.MessageHandler]: Circular reference involving containing bean 'cassandraSinkConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'bridgeMessageHandler' threw exception; nested exception is java.lang.IllegalArgumentException: Invalid CQL insert query syntax: "insert into book (id, isbn, title, author) values (uuid(), ?, ?, ?)"
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
2016-02-22T06:49:50.23-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
2016-02-22T06:49:50.24-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
2016-02-22T06:49:50.24-0800 [APP/0]      ERR 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
2016-02-22T06:49:50.24-0800 [APP/0]      ERR 	at org.springframework.cloud.stream.module.cassandra.sink.CassandraSinkApplication.main(CassandraSinkApplication.java:29)
2016-02-22T06:49:50.24-0800 [APP/0]      ERR 	... 6 more
2016-02-22T06:49:50.24-0800 [APP/0]      ERR Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bridgeMessageHandler' defined in class path resource [org/springframework/cloud/stream/module/cassandra/sink/CassandraSinkConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.messaging.MessageHandler]: Circular reference involving containing bean 'cassandraSinkConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'bridgeMessageHandler' threw exception; nested exception is java.lang.IllegalArgumentException: Invalid CQL insert query syntax: "insert into book (id, isbn, title, author) values (uuid(), ?, ?, ?)"
2016-02-22T06:49:50.24-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
2016-02-22T06:49:50.24-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
2016-02-22T06:49:50.24-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
2016-02-22T06:49:50.24-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
2016-02-22T06:49:50.24-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
2016-02-22T06:49:50.24-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
2016-02-22T06:49:50.24-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.integration.config.annotation.AbstractMethodAnnotationPostProcessor.resolveTargetBeanFromMethodWithBeanAnnotation(AbstractMethodAnnotationPostProcessor.java:389)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.integration.config.annotation.AbstractMethodAnnotationPostProcessor.postProcess(AbstractMethodAnnotationPostProcessor.java:126)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.integration.config.annotation.MessagingAnnotationPostProcessor$1.doWith(MessagingAnnotationPostProcessor.java:168)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:527)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:534)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.integration.config.annotation.MessagingAnnotationPostProcessor.postProcessAfterInitialization(MessagingAnnotationPostProcessor.java:136)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	... 21 more
2016-02-22T06:49:50.25-0800 [APP/0]      ERR Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.messaging.MessageHandler]: Circular reference involving containing bean 'cassandraSinkConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'bridgeMessageHandler' threw exception; nested exception is java.lang.IllegalArgumentException: Invalid CQL insert query syntax: "insert into book (id, isbn, title, author) values (uuid(), ?, ?, ?)"
2016-02-22T06:49:50.25-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	... 38 more
2016-02-22T06:49:50.26-0800 [APP/0]      ERR Caused by: java.lang.IllegalArgumentException: Invalid CQL insert query syntax: "insert into book (id, isbn, title, author) values (uuid(), ?, ?, ?)"
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at org.springframework.cloud.stream.module.cassandra.sink.CassandraSinkConfiguration$PayloadToMatrixTransformer.<init>(CassandraSinkConfiguration.java:158)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at org.springframework.cloud.stream.module.cassandra.sink.CassandraSinkConfiguration.bridgeMessageHandler(CassandraSinkConfiguration.java:86)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at org.springframework.cloud.stream.module.cassandra.sink.CassandraSinkConfiguration$$EnhancerBySpringCGLIB$$79f715b8.CGLIB$bridgeMessageHandler$2(<generated>)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at org.springframework.cloud.stream.module.cassandra.sink.CassandraSinkConfiguration$$EnhancerBySpringCGLIB$$79f715b8$$FastClassBySpringCGLIB$$16ec2f2a.invoke(<generated>)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at org.springframework.cloud.stream.module.cassandra.sink.CassandraSinkConfiguration$$EnhancerBySpringCGLIB$$79f715b8.bridgeMessageHandler(<generated>)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at java.lang.reflect.Method.invoke(Method.java:497)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
2016-02-22T06:49:50.26-0800 [APP/0]      ERR 	... 39 more
2016-02-22T06:49:50.29-0800 [APP/0]      OUT 2016-02-22 14:49:50.296  INFO 17 --- [       Thread-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@256c0210: startup date [Mon Feb 22 14:49:34 UTC 2016]; root of context hierarchy
2016-02-22T06:49:50.29-0800 [APP/0]      OUT 2016-02-22 14:49:50.298  INFO 17 --- [       Thread-2] o.s.c.support.DefaultLifecycleProcessor
```

**Comment by sabbyanandan** [comment]
Comment from @artembilan:

> Somehow in your environment the `insert into book (id, isbn, title, author) values (uuid(), ?, ?, ?)` doesn't match to the pattern `.+\((.+)\).+(?:values\s*\((.+)\))`

**Comment by artembilan** [comment]
Adding more StackTrace to demonstrate how `PayloadToMatrixTransformer` "doesn't like" the `ingestQuery` value.

**Comment by sabbyanandan** [comment]
Hi @ericbottard: any thoughts on Artem's observation?

**Comment by ericbottard** [comment]
Well, what can I say? Using Intellij' regex tester, the regex seems to match the value. We'd need to debug the execution somehow.

**Comment by artembilan** [comment]
Thank you, @ericbottard , for reaching us anyway!

Well, definitely @sabbyanandan can confirm that he made a demo on the matter in not so far past and looks like we have an issue since some latest CF update. @sabbyanandan 's idea that the problem is somewhere with buildpack (fully not sure what is the beast).

From other side I'm not familiar with Spring Boot Dev Tools which looks like intended to help to debug remote Boot applications.

And seems for me I read once some announcement from Ben Hale (not sure it's time to disturb him) about some CF debugging feature. (Correct me otherwise).

**Comment by ericbottard** [comment]
Looks like I don't have the full context. Does this fail on CF only ? Also, any chance there could have been bogus characters in the submitted query (I copy/paster what appeared in this thread to test the regex)

**Comment by artembilan** [comment]
No, you really have a full context:

1. It passes locally - MacOS, Windows, Linux on Bamboo
2. It passed on CF recently. @sabbyanandan did some demo with the same content.
3. It doesn't pass on the current CF. We were pairing with @sabbyanandan yesterday through the ScreenHero.
4. That is really ridiculous because we don't see any bogus characters even in the StackTrace there on CF.

**Comment by ericbottard** [comment]
Hmmm, I bet on https://github.com/spring-cloud/spring-cloud-dataflow-admin-cloudfoundry/commit/e8d3a8e4e872f6aad9e28417bf3fb51c66a0b7c7 then...

**Comment by artembilan** [comment]
Cool! 
Since that is our code we really can debug it! :smile: 

Can you give it a shot? Or should I play?
I'm asking because it looks like you are guilty and that should be enough easy for you to do that in the opened project.

**Comment by ericbottard** [comment]
Ah ah :)
You have no idea how long it took me to arrive at that commit.

I'll try to first confirm it is indeed the culprit. Can you confirm I can witness the error without actually having to deal with Cassandra (_i.e._ it fails at startup)?

**Comment by ericbottard** [comment]
It's weird though, as the exception thrown seems to see the correct query (_i.e._ escaping worked as expected).

**Comment by artembilan** [comment]
Right, it fails on start up: 
```
public PayloadToMatrixTransformer(String query) {
			Matcher matcher = PATTERN.matcher(query);
			if (matcher.matches()) {
			.....
			}
			else {
				throw new IllegalArgumentException("Invalid CQL insert query syntax: " + query);
			}
			....
		}
```
The incoming `query` doesn't match to the pattern.

Not sure that we need the full Cassandra integration test pack.
Looks like it is just enough to test incoming property against some testing regexp.
